- name: Gather serial number
  command: "sudo dmidecode -s system-serial-number"
  register: serial_output
  delegate_to: "{{ item }}"

- name: Build the host_info dictionary
  set_fact:
    host_info: "{{ host_info | default({}) | combine({item: {'serial_number': serial_output.stdout, 'cluster_name': cluster_name }}) }}"
